@baseUrl= http://localhost:3333
@token={{Authenticate.response.body.access_token}}

# @name Create_Account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "John Doe",
  "email": "teste@email.com",
  "password": "123456"
}

###

# @name Authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "teste@email.com",
  "password": "123456"
}
###

# @name Create_Question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Qual é o seu nome?",
  "content": "Qual é o seu nome completo?"
}
###

# @name List_All_Questions
GET {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{token}}
###

# @name List_Questions_Paginated
GET {{baseUrl}}/questions?page=1&limit=1&sort=desc&orderBy=createdAt
Content-Type: application/json
Authorization: Bearer {{token}}