version: '3.8'

services:
  postgres:
    container_name: postgres-nest-clean
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nest-clean
    volumes:
      - ./data/pg:/data/postgres
